[build]
  command = "npm install && npx tsc"
  publish = "public"

[functions]
  directory = "netlify/functions"
  node_bundler = "nft"
  included_files = ["src/views/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
